name: Sanity Check

# Quando rodar? Em todo Push na main ou Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: DATA SCIENCE INTEGRITY
  data-science-build:
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout do C칩digo
        uses: actions/checkout@v4

      - name: 游냡 Build Docker (Data Science)
        # Tenta construir a imagem. Se o Dockerfile estiver errado, falha aqui.
        run: |
          cd data-science
          docker build -t churn-api-test .

      - name: 游냀 Setup Python (Para testes unit치rios)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 游닍 Instalar Depend칡ncias e Rodar Pytest
        # Roda os testes unit치rios (test_api.py) para garantir que a l칩gica n칚o quebrou
        run: |
          cd data-science
          pip install -r requirements.txt
          pytest

  # JOB 2: BACKEND INTEGRITY (Placeholder para o Java)
  # backend-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     ... (Configura칞칚o futura do Java)